services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: [ "CMD-SHELL", "echo ruok | nc localhost 2181 | grep imok || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - casino
  kafka:
    image: confluentinc/cp-server:7.2.1
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9997:9997"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka
    healthcheck:
      test: [ "CMD", "bash", "-c", "broker-topics --bootstrap-server localhost:9092 --list > /dev/null 2>&1" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - casino
    volumes:
      - kafka_data:/var/lib/kafka/data
  kafka-ui:
    container_name: broker-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8082:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    depends_on:
      - zookeeper
    networks:
      - casino
  postgres:
    container_name: transactions_db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_transactions_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - casino
  tx_migrations:
    image: ghcr.io/kukymbr/goose-docker:3.26.0
    restart: no
    depends_on:
      postgres:
        condition: service_healthy

    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=transactions_db port=5432 user=tx_manager password=password dbname=tx_manager
      - GOOSE_VERBOSE=true
      - GOOSE_COMMAND=up
    volumes:
      - ../migrations/tx_manager:/migrations
    networks:
      - casino
  init-kafka:
    image: confluentinc/cp-server:7.2.1
    networks:
      - casino
    depends_on:
      - kafka
    command: >
      /bin/sh -c "
        /bin/kafka-topics --create --if-not-exists --topic casino_transactions --replication-factor=1 --partitions=3 --bootstrap-server kafka:9092;
        /bin/kafka-topics --create --if-not-exists --topic casino_dlq --replication-factor=1 --partitions=1 --bootstrap-server kafka:9092
      "

volumes:
  postgres_transactions_data:
  kafka_data:

networks:
  casino:
    driver: bridge
